config/routes.rb
Rails.application.routes.draw do

  devise_for :users
	root "posts#index"

	resources :posts do
		resources :comments
	end

	resources :about, only: [:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, dependent: :destroy
						# If you set the :dependent option to, :destroy, 
						# it causes all the associated objects to also be destroyed.
						# This way if a post is destroyed, its comments will as well,
						# rather than being left in the DB taking up space.
	validates :title, presence: true
	validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	def index
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
					#authenticate evrything but index and show pages
	def index
		@posts = Post.all.order('created_at DESC')
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to @post
		else
			render 'new' # use render instead of redirect for forms that have data that can be lost if .save fails
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to root_path	# or root
	end

	private

	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/about/about.html.erb
<h1>The About Page</h1>

app/views/about/index.html.erb
<h1>About Me</h1>

<span>Detail and leadership oriented Web Developer with a background in user experience, sales, teaching, and cognitive science. Passionate about the fundamentals of human-computer interaction, object oriented programming, pair programming, and positive team dynamics. In my free time, I’m an avid chess player, video game buff, and fitness enthusiast.</span>

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><h2><%= comment.name %></h2></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> ago</p>
	</div>

	<% if user_signed_in? %>
		<p><%= link_to "Delete", [comment.post, comment],
						method: :delete, 
						class: "button", 
						data: { confirm: "Are you sure?" } %>
		</p>
	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
									<!-- .build is like .new but used for through associations -->
	<p>
		<%= f.label :name %> <br>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :body %> <br>
		<%= f.text_area :body %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div id="navbar">
  		<div id="logo">
  			<%= link_to root_path do %>
  				<%= image_tag("logo.png", :alt => "rss feed", :height =>"45", :width => "70") %>
  			<% end %>	
  		</div>
  		<div id="about">
        <% if !current_page?(root_path) %>
  			 <p class="links"><%= link_to "Blog", root_path %></p>
        <% end %>

        <% if !current_page?(about_index_path) %>
  			 <p class="about-blog"><%= link_to "About", about_index_path %></p>
        <% end %>
  		</div>

      <div id="social-media">
    		<ul>
    			<li><a class="links" href="https://www.linkedin.com/in/btbernheim/">LinkedIn</li>
    			<li><a class="links" href="https://github.com/btbernheim">GitHub</li>
    			<li><a class="links" href="https://www.facebook.com/brian.bernheim">FaceBook</li>
    		</ul>
      </div>

      <h1 id="title">Personal Blog</h1>

      <% if !user_signed_in? %>
          <button id="login" class="sign_in"><%= link_to("Login", new_user_session_path) %> </button> 
          <button id="register" class="sign_in"><%= link_to("Register", new_user_registration_path) %></button>
      <% end %>
  	</div>

  	<div id="main_content">
  		<div id="header">

        <% if current_page?(root_path) %>
          <h3>All Posts</h3>
        <% else %>
          <%= link_to "Back To All Posts", root_path %>
        <% end %>

        <% if user_signed_in? %>
    			<div class="buttons">
    				<button class="button"><%= link_to("New Post", new_post_path) %></button>
    				<button class="button"><%= link_to("Log Out", destroy_user_session_path, method: :delete) %>﻿</button>
    			</div>
        <% end %>

  		</div>

  		<% flash.each do |name, msg| %>
  			<%= content_tag(:div, msg, class: "alert") %>
  			<!-- content_tag() builds an HTML5 block tag of name and content -->
  		<% end %>

  	</div>

    <%= yield %>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving.</h2>
			<ul>
				<% @post.errors.full_messages.each do |error|%>
					<li><%= error %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>

	<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post Page</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Welcome To the Blog</h1>

<% @posts.each do |post| %>
	<div class="post_wrapper">
		<h2 class="title"> 
			<%= link_to post.title, post %> 
		</h2>
		<p class="date">
			<%= post.created_at.strftime("%B, %d, %Y") %>
		</p>
	</div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1>Create A New Post</h1>

	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
	<h1 class="title">
		<%= @post.title %>
	</h1>
	<p class="date">
		Submitted <%= time_ago_in_words(@post.created_at) %> ago <br>
		<% if @post.created_at != @post.updated_at %> 
		<!-- Add feature to show submission  -->
			Updated <%= time_ago_in_words(@post.updated_at) %> ago
		<% end %>
	</p>

	<div id="edit_delete_home">
		<% if user_signed_in? %>
			<p><%= link_to 'Edit', edit_post_path(@post) %></p>
			<p><%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: "Are you sure?" } %></p>
													<!-- method: tells rails what the link_to is doing i.e. dleteing, data: will dispay a pop up to ask a question before competing the request. -->
			<p><%= link_to 'Home', root_path %></p>
		<% end %>
	</div>

	<p class="body">
		<%= @post.body %>
	</p>

	<div id="comments">
		<h2><%= @post.comments.count %> Comments</h2>
		<%= render @post.comments %>

		<h3>Add A Comment</h3>
		<%= render "comments/form" %>
	</div>
</div>